name: Convert files

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  convert_files:
    runs-on: ubuntu-20.04
    container: python:3.11.1-bullseye
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update apt cache
        run: apt-get update

      - name: Install tex
        run: apt-get -y install texlive-latex-base texlive-latex-extra texlive-latex-recommended latexmk

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Convert input files
        run: python3 -m rules_doc_generator

      - name: Create pdf output
        run: latexmk -pdf -jobname=latex/demo latex/demo.tex

      - name: Upload pdf output
        uses: actions/upload-artifact@v3
        with:
          name: pdf-output
          path: latex/demo.pdf

      - name: Upload pdf output
        uses: actions/upload-artifact@v3
        with:
          name: html-output
          path: html/*

  deploy:
    if: github.repository == 'rubenpieters/netrunner-comprehensive-rules '
    needs: convert_files
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: html-output
          path: '.'

      - name: Move index.html
        run: mv demo.html index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
