name: Convert files

on: push

jobs:
  convert_files:
    runs-on: ubuntu-20.04
    container: python:3.11.1-bullseye
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update apt cache
        run: apt-get update

      - name: Install tex
        run: apt-get -y install texlive-latex-base texlive-latex-extra texlive-latex-recommended latexmk

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Convert input files
        run: python3 -m rules_doc_generator

      - name: Create pdf output
        run: latexmk -pdf -jobname=latex/demo latex/demo.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            latex/demo.pdf
            html/demo.html
